export const GOOGLE_STRATEGY = 'GOOGLE_STRATEGY';
export const GOOGLE_PASSWORD = 'GOOGLE_PASSWORD';
export const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
export const GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
